# This configuration is intended for staging/demo purpose
version: "3.8"
services:
  lorem-words-processing:
    image: "know-how.download/sample-lorem-mix-words-processing:latest"
    container_name: lorem-demo-words-processing
    restart: no
    depends_on:
      - kafka
    ports:
      - "8085:8085"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=lorem-demo-kafka:9092

  lorem-reports-history:
    image: "know-how.download/sample-lorem-mix-reports-history:latest"
    container_name: lorem-demo-reports-history
    restart: no
    depends_on:
      - postgres
      - kafka
    ports:
      - "8086:8086"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lorem_db
      - KAFKA_BOOTSTRAP_SERVERS=lorem-demo-kafka:9092
      - DATASOURCE_URL=jdbc:postgresql://lorem-demo-postgres:5432/lorem_db

  postgres:
    image: "postgres:16.6"
    container_name: lorem-demo-postgres
    restart: no
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lorem_db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.3
    container_name: lorem-demo-zookeeper
    restart: no
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: lorem-demo-kafka
    restart: no
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
